bruk uv til publishing (dry-run)

diff --git a/.github/workflows/publish_pypi.yml b/.github/workflows/publish_pypi.yml
--- a/.github/workflows/publish_pypi.yml
+++ b/.github/workflows/publish_pypi.yml
@@ -1,22 +1,44 @@
 name: Release
 
 on:
-  release:
-    types: [published]
+  workflow_dispatch:
+#  release:
+#    types: [published]
 
 jobs:
   publish-pypi:
     runs-on: ubuntu-latest
     permissions:
       id-token: write
+    env:
+      TAG: 0.0.1 #${{ github.ref_name }}
     steps:
-      - uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+      - name: Validate tag format
+        run: |
+          if [[ "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "::notice::Tag name format is valid."
+          else
+            echo "::error::Invalid tag name. Must conform to major.minor.patch format (e.g., 1.2.3)."
+            exit 1
+          fi
+
+      - name: Checkout code
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
+
+      - name: Set up Python
+        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
         with:
           python-version: 3.11
+
+      - name: Install uv
+        run: pip3 install --user uv
+
       - name: Set version
-        run: sed -i "s/version =.*/version = $(echo -n \"${{ github.ref }}\" | sed "s/refs\/tags\///")/" pyproject.toml
-      - run: pip3 install --user poetry
-      - run: poetry build
-      - name: Publish package distributions to PyPI
-        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
+        run: uv version "$TAG"
+
+      - name: Build
+        run: uv build
+
+      # authentication via https://docs.pypi.org/trusted-publishers/
+      - name: Publish
+        run: uv publish --trusted-publishing always --dry-run
